

CREATE FUNCTION .DBO.STRING_SPLIT (@STRING_CHAR VARCHAR(8000), @SPLIT_CHAR VARCHAR(5))
RETURNS @RESULT_TABLE TABLE (ID INT IDENTITY, SPLIT_CHAR VARCHAR(8000))
AS

BEGIN
--DECLARE @STRING_CHAR AS VARCHAR(8000)
--DECLARE @ACCOUNTNO VARCHAR(20)
--DECLARE @SPLIT_CHAR AS VARCHAR(5)
DECLARE @STRING_CHAR_AUX AS VARCHAR(8000)
DECLARE @COUNT AS INT
DECLARE @AUX_COUNT AS INT
DECLARE @LEN_CHAR AS INT


--SET @STRING_CHAR = '4864-6963 // 15-5722-6799'
--SET @ACCOUNTNO = 'A131206469893587AALD'
--SET @SPLIT_CHAR = '//' 
SET @COUNT = 0

SET @STRING_CHAR_AUX = @STRING_CHAR +  @SPLIT_CHAR

SELECT @LEN_CHAR = LEN(@STRING_CHAR)

--SELECT @STRING_CHAR
--SELECT @LEN_CHAR 

WHILE @COUNT <= @LEN_CHAR
BEGIN

	--SELECT @STRING_CHAR, @COUNT, CHARINDEX(@SPLIT_CHAR,@STRING_CHAR)

	INSERT INTO @RESULT_TABLE (SPLIT_CHAR)
	SELECT 
		  LTRIM( RTRIM( SUBSTRING(@STRING_CHAR_AUX, @COUNT, CHARINDEX(@SPLIT_CHAR,SUBSTRING(@STRING_CHAR_AUX, @COUNT, @LEN_CHAR))-1 ) ))

	SET @COUNT = @COUNT + CHARINDEX(@SPLIT_CHAR,@STRING_CHAR_AUX) + LEN(@SPLIT_CHAR)

END 

RETURN 

END 

/*
	TEST DE EJECUCION
	
	SELECT * FROM .DBO.STRING_SPLIT ('668549 |  564646', '|')
	SELECT * FROM .DBO.STRING_SPLIT ('2256787|564646|KJFKSGFDSL', '|')

	SELECT * FROM .DBO.STRING_SPLIT ('LUCAS , KKASDALA, OOEBKSDJA, JSHFAKSHAS', ',')
	
	
	SELECT * FROM .DBO.STRING_SPLIT ('668549 |  564646', '|')
	UNION ALL
	SELECT * FROM .DBO.STRING_SPLIT ('2256787|564646|KJFKSGFDSL', '|')
    UNION ALL
	SELECT * FROM .DBO.STRING_SPLIT ('LUCAS , KKASDALA, OOEBKSDJA, JSHFAKSHAS', ',')
	

*/
